
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Accordion': typeof import("../client/components/Accordion.vue")['default']
    'Breadcrumbs': typeof import("../client/components/Breadcrumbs.vue")['default']
    'DialogModal': typeof import("../client/components/DialogModal.vue")['default']
    'Dropdown': typeof import("../client/components/Dropdown.vue")['default']
    'Modal': typeof import("../client/components/Modal.vue")['default']
    'Pagination': typeof import("../client/components/Pagination.vue")['default']
    'AdminCategoriesNested': typeof import("../client/components/admin/categories/nested.vue")['default']
    'AdminDialogsMedia': typeof import("../client/components/admin/dialogs/media.vue")['default']
    'AdminHeader': typeof import("../client/components/admin/header.vue")['default']
    'AdminSidebar': typeof import("../client/components/admin/sidebar.vue")['default']
    'CardPreviewMedia': typeof import("../client/components/card/previewMedia.vue")['default']
    'CartAside': typeof import("../client/components/cart/aside.vue")['default']
    'CartButton': typeof import("../client/components/cart/button.vue")['default']
    'CartCard': typeof import("../client/components/cart/card.vue")['default']
    'CartContent': typeof import("../client/components/cart/content.vue")['default']
    'CartSidebar': typeof import("../client/components/cart/sidebar.vue")['default']
    'CatalogAside': typeof import("../client/components/catalog/aside.vue")['default']
    'CatalogCard': typeof import("../client/components/catalog/card.vue")['default']
    'CatalogContent': typeof import("../client/components/catalog/content.vue")['default']
    'CatalogSidebar': typeof import("../client/components/catalog/sidebar.vue")['default']
    'CustomDatepicker': typeof import("../client/components/custom/datepicker.vue")['default']
    'CustomMultiSelect': typeof import("../client/components/custom/multiSelect.vue")['default']
    'DefaultHeader': typeof import("../client/components/default/header.vue")['default']
    'DialogsAdminCategory': typeof import("../client/components/dialogs/admin/category.vue")['default']
    'DialogsAdminProduct': typeof import("../client/components/dialogs/admin/product.vue")['default']
    'DialogsAdminTag': typeof import("../client/components/dialogs/admin/tag.vue")['default']
    'DialogsAdminUser': typeof import("../client/components/dialogs/admin/user.vue")['default']
    'DialogsAuthLogin': typeof import("../client/components/dialogs/auth/login.vue")['default']
    'DialogsAuthRecovery': typeof import("../client/components/dialogs/auth/recovery.vue")['default']
    'DialogsAuthRegister': typeof import("../client/components/dialogs/auth/register.vue")['default']
    'DialogsCartOrder': typeof import("../client/components/dialogs/cart/order.vue")['default']
    'DialogsCartProduct': typeof import("../client/components/dialogs/cart/product.vue")['default']
    'DialogsCatalogProduct': typeof import("../client/components/dialogs/catalog/product.vue")['default']
    'DialogsTemplateProduct': typeof import("../client/components/dialogs/template/product.vue")['default']
    'SwiperProduct': typeof import("../client/components/swiper/product.vue")['default']
    'UiButtonDanger': typeof import("../client/components/ui/button/danger.vue")['default']
    'UiButtonPrimary': typeof import("../client/components/ui/button/primary.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAccordion': typeof import("../client/components/Accordion.vue")['default']
    'LazyBreadcrumbs': typeof import("../client/components/Breadcrumbs.vue")['default']
    'LazyDialogModal': typeof import("../client/components/DialogModal.vue")['default']
    'LazyDropdown': typeof import("../client/components/Dropdown.vue")['default']
    'LazyModal': typeof import("../client/components/Modal.vue")['default']
    'LazyPagination': typeof import("../client/components/Pagination.vue")['default']
    'LazyAdminCategoriesNested': typeof import("../client/components/admin/categories/nested.vue")['default']
    'LazyAdminDialogsMedia': typeof import("../client/components/admin/dialogs/media.vue")['default']
    'LazyAdminHeader': typeof import("../client/components/admin/header.vue")['default']
    'LazyAdminSidebar': typeof import("../client/components/admin/sidebar.vue")['default']
    'LazyCardPreviewMedia': typeof import("../client/components/card/previewMedia.vue")['default']
    'LazyCartAside': typeof import("../client/components/cart/aside.vue")['default']
    'LazyCartButton': typeof import("../client/components/cart/button.vue")['default']
    'LazyCartCard': typeof import("../client/components/cart/card.vue")['default']
    'LazyCartContent': typeof import("../client/components/cart/content.vue")['default']
    'LazyCartSidebar': typeof import("../client/components/cart/sidebar.vue")['default']
    'LazyCatalogAside': typeof import("../client/components/catalog/aside.vue")['default']
    'LazyCatalogCard': typeof import("../client/components/catalog/card.vue")['default']
    'LazyCatalogContent': typeof import("../client/components/catalog/content.vue")['default']
    'LazyCatalogSidebar': typeof import("../client/components/catalog/sidebar.vue")['default']
    'LazyCustomDatepicker': typeof import("../client/components/custom/datepicker.vue")['default']
    'LazyCustomMultiSelect': typeof import("../client/components/custom/multiSelect.vue")['default']
    'LazyDefaultHeader': typeof import("../client/components/default/header.vue")['default']
    'LazyDialogsAdminCategory': typeof import("../client/components/dialogs/admin/category.vue")['default']
    'LazyDialogsAdminProduct': typeof import("../client/components/dialogs/admin/product.vue")['default']
    'LazyDialogsAdminTag': typeof import("../client/components/dialogs/admin/tag.vue")['default']
    'LazyDialogsAdminUser': typeof import("../client/components/dialogs/admin/user.vue")['default']
    'LazyDialogsAuthLogin': typeof import("../client/components/dialogs/auth/login.vue")['default']
    'LazyDialogsAuthRecovery': typeof import("../client/components/dialogs/auth/recovery.vue")['default']
    'LazyDialogsAuthRegister': typeof import("../client/components/dialogs/auth/register.vue")['default']
    'LazyDialogsCartOrder': typeof import("../client/components/dialogs/cart/order.vue")['default']
    'LazyDialogsCartProduct': typeof import("../client/components/dialogs/cart/product.vue")['default']
    'LazyDialogsCatalogProduct': typeof import("../client/components/dialogs/catalog/product.vue")['default']
    'LazyDialogsTemplateProduct': typeof import("../client/components/dialogs/template/product.vue")['default']
    'LazySwiperProduct': typeof import("../client/components/swiper/product.vue")['default']
    'LazyUiButtonDanger': typeof import("../client/components/ui/button/danger.vue")['default']
    'LazyUiButtonPrimary': typeof import("../client/components/ui/button/primary.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Accordion: typeof import("../client/components/Accordion.vue")['default']
export const Breadcrumbs: typeof import("../client/components/Breadcrumbs.vue")['default']
export const DialogModal: typeof import("../client/components/DialogModal.vue")['default']
export const Dropdown: typeof import("../client/components/Dropdown.vue")['default']
export const Modal: typeof import("../client/components/Modal.vue")['default']
export const Pagination: typeof import("../client/components/Pagination.vue")['default']
export const AdminCategoriesNested: typeof import("../client/components/admin/categories/nested.vue")['default']
export const AdminDialogsMedia: typeof import("../client/components/admin/dialogs/media.vue")['default']
export const AdminHeader: typeof import("../client/components/admin/header.vue")['default']
export const AdminSidebar: typeof import("../client/components/admin/sidebar.vue")['default']
export const CardPreviewMedia: typeof import("../client/components/card/previewMedia.vue")['default']
export const CartAside: typeof import("../client/components/cart/aside.vue")['default']
export const CartButton: typeof import("../client/components/cart/button.vue")['default']
export const CartCard: typeof import("../client/components/cart/card.vue")['default']
export const CartContent: typeof import("../client/components/cart/content.vue")['default']
export const CartSidebar: typeof import("../client/components/cart/sidebar.vue")['default']
export const CatalogAside: typeof import("../client/components/catalog/aside.vue")['default']
export const CatalogCard: typeof import("../client/components/catalog/card.vue")['default']
export const CatalogContent: typeof import("../client/components/catalog/content.vue")['default']
export const CatalogSidebar: typeof import("../client/components/catalog/sidebar.vue")['default']
export const CustomDatepicker: typeof import("../client/components/custom/datepicker.vue")['default']
export const CustomMultiSelect: typeof import("../client/components/custom/multiSelect.vue")['default']
export const DefaultHeader: typeof import("../client/components/default/header.vue")['default']
export const DialogsAdminCategory: typeof import("../client/components/dialogs/admin/category.vue")['default']
export const DialogsAdminProduct: typeof import("../client/components/dialogs/admin/product.vue")['default']
export const DialogsAdminTag: typeof import("../client/components/dialogs/admin/tag.vue")['default']
export const DialogsAdminUser: typeof import("../client/components/dialogs/admin/user.vue")['default']
export const DialogsAuthLogin: typeof import("../client/components/dialogs/auth/login.vue")['default']
export const DialogsAuthRecovery: typeof import("../client/components/dialogs/auth/recovery.vue")['default']
export const DialogsAuthRegister: typeof import("../client/components/dialogs/auth/register.vue")['default']
export const DialogsCartOrder: typeof import("../client/components/dialogs/cart/order.vue")['default']
export const DialogsCartProduct: typeof import("../client/components/dialogs/cart/product.vue")['default']
export const DialogsCatalogProduct: typeof import("../client/components/dialogs/catalog/product.vue")['default']
export const DialogsTemplateProduct: typeof import("../client/components/dialogs/template/product.vue")['default']
export const SwiperProduct: typeof import("../client/components/swiper/product.vue")['default']
export const UiButtonDanger: typeof import("../client/components/ui/button/danger.vue")['default']
export const UiButtonPrimary: typeof import("../client/components/ui/button/primary.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAccordion: typeof import("../client/components/Accordion.vue")['default']
export const LazyBreadcrumbs: typeof import("../client/components/Breadcrumbs.vue")['default']
export const LazyDialogModal: typeof import("../client/components/DialogModal.vue")['default']
export const LazyDropdown: typeof import("../client/components/Dropdown.vue")['default']
export const LazyModal: typeof import("../client/components/Modal.vue")['default']
export const LazyPagination: typeof import("../client/components/Pagination.vue")['default']
export const LazyAdminCategoriesNested: typeof import("../client/components/admin/categories/nested.vue")['default']
export const LazyAdminDialogsMedia: typeof import("../client/components/admin/dialogs/media.vue")['default']
export const LazyAdminHeader: typeof import("../client/components/admin/header.vue")['default']
export const LazyAdminSidebar: typeof import("../client/components/admin/sidebar.vue")['default']
export const LazyCardPreviewMedia: typeof import("../client/components/card/previewMedia.vue")['default']
export const LazyCartAside: typeof import("../client/components/cart/aside.vue")['default']
export const LazyCartButton: typeof import("../client/components/cart/button.vue")['default']
export const LazyCartCard: typeof import("../client/components/cart/card.vue")['default']
export const LazyCartContent: typeof import("../client/components/cart/content.vue")['default']
export const LazyCartSidebar: typeof import("../client/components/cart/sidebar.vue")['default']
export const LazyCatalogAside: typeof import("../client/components/catalog/aside.vue")['default']
export const LazyCatalogCard: typeof import("../client/components/catalog/card.vue")['default']
export const LazyCatalogContent: typeof import("../client/components/catalog/content.vue")['default']
export const LazyCatalogSidebar: typeof import("../client/components/catalog/sidebar.vue")['default']
export const LazyCustomDatepicker: typeof import("../client/components/custom/datepicker.vue")['default']
export const LazyCustomMultiSelect: typeof import("../client/components/custom/multiSelect.vue")['default']
export const LazyDefaultHeader: typeof import("../client/components/default/header.vue")['default']
export const LazyDialogsAdminCategory: typeof import("../client/components/dialogs/admin/category.vue")['default']
export const LazyDialogsAdminProduct: typeof import("../client/components/dialogs/admin/product.vue")['default']
export const LazyDialogsAdminTag: typeof import("../client/components/dialogs/admin/tag.vue")['default']
export const LazyDialogsAdminUser: typeof import("../client/components/dialogs/admin/user.vue")['default']
export const LazyDialogsAuthLogin: typeof import("../client/components/dialogs/auth/login.vue")['default']
export const LazyDialogsAuthRecovery: typeof import("../client/components/dialogs/auth/recovery.vue")['default']
export const LazyDialogsAuthRegister: typeof import("../client/components/dialogs/auth/register.vue")['default']
export const LazyDialogsCartOrder: typeof import("../client/components/dialogs/cart/order.vue")['default']
export const LazyDialogsCartProduct: typeof import("../client/components/dialogs/cart/product.vue")['default']
export const LazyDialogsCatalogProduct: typeof import("../client/components/dialogs/catalog/product.vue")['default']
export const LazyDialogsTemplateProduct: typeof import("../client/components/dialogs/template/product.vue")['default']
export const LazySwiperProduct: typeof import("../client/components/swiper/product.vue")['default']
export const LazyUiButtonDanger: typeof import("../client/components/ui/button/danger.vue")['default']
export const LazyUiButtonPrimary: typeof import("../client/components/ui/button/primary.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
