// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 05/11/2024, 22:48:25
const configMerger = require("/home/andrew/www/slovo-book/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/andrew/www/slovo-book/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/andrew/www/slovo-book/client/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/andrew/www/slovo-book/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/andrew/www/slovo-book/client/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/andrew/www/slovo-book/client/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/andrew/www/slovo-book/client/plugins/**/*.{js,ts,mjs}","/home/andrew/www/slovo-book/client/composables/**/*.{js,ts,mjs}","/home/andrew/www/slovo-book/client/utils/**/*.{js,ts,mjs}","/home/andrew/www/slovo-book/client/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/andrew/www/slovo-book/client/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/andrew/www/slovo-book/client/app.config.{js,ts,mjs}"] }));

module.exports = config
